import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

class ForgeConfig {
  const ForgeConfig({
    required this.appName,
    required this.modules,
  });

  final String appName;
  final List<String> modules;

  static const String fileName = '.flutterforge.yaml';

  static bool existsIn(String projectPath) {
    return File(p.join(projectPath, fileName)).existsSync();
  }

  static ForgeConfig? load(String projectPath) {
    final file = File(p.join(projectPath, fileName));
    if (!file.existsSync()) return null;

    final content = file.readAsStringSync();
    final yaml = loadYaml(content);
    if (yaml is! YamlMap) return null;

    final appName = yaml['app_name'] as String?;
    final modulesList = yaml['modules'] as YamlList?;
    if (appName == null || modulesList == null) return null;

    return ForgeConfig(
      appName: appName,
      modules: modulesList.cast<String>().toList(),
    );
  }

  Future<void> save(String projectPath) async {
    final file = File(p.join(projectPath, fileName));
    final modulesYaml = modules.map((m) => '  - $m').join('\n');
    final content = '''# Generated by FlutterForge - do not edit manually
app_name: $appName
modules:
$modulesYaml
''';
    await file.writeAsString(content);
  }

  ForgeConfig withModules(List<String> additionalModules) {
    final merged = [...modules];
    for (final m in additionalModules) {
      if (!merged.contains(m)) merged.add(m);
    }
    return ForgeConfig(appName: appName, modules: merged);
  }
}
