import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

import 'package:flutterforge/src/config/cicd_config.dart';

class ForgeConfig {
  const ForgeConfig({
    required this.appName,
    required this.modules,
    this.cicdConfig,
  });

  final String appName;
  final List<String> modules;
  final CicdConfig? cicdConfig;

  static const String fileName = '.flutterforge.yaml';

  static bool existsIn(String projectPath) {
    return File(p.join(projectPath, fileName)).existsSync();
  }

  static ForgeConfig? load(String projectPath) {
    final file = File(p.join(projectPath, fileName));
    if (!file.existsSync()) return null;

    final content = file.readAsStringSync();
    final yaml = loadYaml(content);
    if (yaml is! YamlMap) return null;

    final appName = yaml['app_name'] as String?;
    final modulesList = yaml['modules'] as YamlList?;
    if (appName == null || modulesList == null) return null;

    final cicd = CicdConfig.fromYaml(yaml['cicd'] as YamlMap?);

    return ForgeConfig(
      appName: appName,
      modules: modulesList.cast<String>().toList(),
      cicdConfig: cicd,
    );
  }

  Future<void> save(String projectPath) async {
    final file = File(p.join(projectPath, fileName));
    final modulesYaml = modules.map((m) => '  - $m').join('\n');
    final buffer = StringBuffer();
    buffer.writeln('# Generated by FlutterForge - do not edit manually');
    buffer.writeln('app_name: $appName');
    buffer.writeln('modules:');
    buffer.writeln(modulesYaml);
    if (cicdConfig != null) {
      for (final line in cicdConfig!.toYamlLines()) {
        buffer.writeln(line);
      }
    }
    await file.writeAsString(buffer.toString());
  }

  ForgeConfig withModules(List<String> additionalModules) {
    final merged = [...modules];
    for (final m in additionalModules) {
      if (!merged.contains(m)) merged.add(m);
    }
    return ForgeConfig(appName: appName, modules: merged, cicdConfig: cicdConfig);
  }

  ForgeConfig withoutModules(List<String> moduleIdsToRemove) {
    final remaining = modules.where((m) => !moduleIdsToRemove.contains(m)).toList();
    // Clear cicd config if cicd module is being removed
    final keepCicd = !moduleIdsToRemove.contains('cicd') ? cicdConfig : null;
    return ForgeConfig(appName: appName, modules: remaining, cicdConfig: keepCicd);
  }

  ForgeConfig withCicdConfig(CicdConfig config) {
    return ForgeConfig(appName: appName, modules: modules, cicdConfig: config);
  }
}
