import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

import 'package:flutterforge/src/config/cicd_config.dart';
import 'package:flutterforge/src/config/flavors_config.dart';

class ForgeConfig {
  const ForgeConfig({
    required this.appName,
    required this.modules,
    this.org = 'com.example',
    this.cicdConfig,
    this.flavorsConfig,
    this.platforms = const ['android', 'ios'],
  });

  final String appName;
  final String org;
  final List<String> modules;
  final CicdConfig? cicdConfig;
  final FlavorsConfig? flavorsConfig;
  final List<String> platforms;

  static const String fileName = '.flutterforge.yaml';

  static bool existsIn(String projectPath) {
    return File(p.join(projectPath, fileName)).existsSync();
  }

  static ForgeConfig? load(String projectPath) {
    final file = File(p.join(projectPath, fileName));
    if (!file.existsSync()) return null;

    final content = file.readAsStringSync();
    final yaml = loadYaml(content);
    if (yaml is! YamlMap) return null;

    final appName = yaml['app_name'] as String?;
    final org = yaml['org'] as String? ?? 'com.example';
    final modulesList = yaml['modules'] as YamlList?;
    if (appName == null || modulesList == null) return null;

    final cicd = CicdConfig.fromYaml(yaml['cicd'] as YamlMap?);
    final flavors = FlavorsConfig.fromYaml(yaml['flavors'] as YamlMap?);

    // Backward compat: default to android + ios when key is absent
    final platformsList = yaml['platforms'] as YamlList?;
    final platforms =
        platformsList?.cast<String>().toList() ?? const ['android', 'ios'];

    return ForgeConfig(
      appName: appName,
      org: org,
      modules: modulesList.cast<String>().toList(),
      cicdConfig: cicd,
      flavorsConfig: flavors,
      platforms: platforms,
    );
  }

  Future<void> save(String projectPath) async {
    final file = File(p.join(projectPath, fileName));
    final buffer = StringBuffer();
    buffer.writeln('# Generated by FlutterForge - do not edit manually');
    buffer.writeln('app_name: $appName');
    buffer.writeln('org: $org');
    buffer.writeln('platforms:');
    for (final platform in platforms) {
      buffer.writeln('  - $platform');
    }
    buffer.writeln('modules:');
    for (final m in modules) {
      buffer.writeln('  - $m');
    }
    if (cicdConfig != null) {
      for (final line in cicdConfig!.toYamlLines()) {
        buffer.writeln(line);
      }
    }
    if (flavorsConfig != null) {
      for (final line in flavorsConfig!.toYamlLines()) {
        buffer.writeln(line);
      }
    }
    await file.writeAsString(buffer.toString());
  }

  ForgeConfig withModules(List<String> additionalModules) {
    final merged = [...modules];
    for (final m in additionalModules) {
      if (!merged.contains(m)) merged.add(m);
    }
    return ForgeConfig(appName: appName, org: org, modules: merged, cicdConfig: cicdConfig, flavorsConfig: flavorsConfig, platforms: platforms);
  }

  ForgeConfig withoutModules(List<String> moduleIdsToRemove) {
    final remaining = modules.where((m) => !moduleIdsToRemove.contains(m)).toList();
    final keepCicd = !moduleIdsToRemove.contains('cicd') ? cicdConfig : null;
    final keepFlavors = !moduleIdsToRemove.contains('flavors') ? flavorsConfig : null;
    return ForgeConfig(appName: appName, org: org, modules: remaining, cicdConfig: keepCicd, flavorsConfig: keepFlavors, platforms: platforms);
  }

  ForgeConfig withCicdConfig(CicdConfig config) {
    return ForgeConfig(appName: appName, org: org, modules: modules, cicdConfig: config, flavorsConfig: flavorsConfig, platforms: platforms);
  }

  ForgeConfig withFlavorsConfig(FlavorsConfig config) {
    return ForgeConfig(appName: appName, org: org, modules: modules, cicdConfig: cicdConfig, flavorsConfig: config, platforms: platforms);
  }

  ForgeConfig withPlatforms(List<String> newPlatforms) {
    final merged = [...platforms];
    for (final p in newPlatforms) {
      if (!merged.contains(p)) merged.add(p);
    }
    return ForgeConfig(appName: appName, org: org, modules: modules, cicdConfig: cicdConfig, flavorsConfig: flavorsConfig, platforms: merged);
  }

  ForgeConfig withoutPlatforms(List<String> platformIdsToRemove) {
    final remaining = platforms.where((p) => !platformIdsToRemove.contains(p)).toList();
    return ForgeConfig(appName: appName, org: org, modules: modules, cicdConfig: cicdConfig, flavorsConfig: flavorsConfig, platforms: remaining);
  }
}
